# Credit Scoring & PD Model

## Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Datensatz

In [12]:
df_train = pd.read_csv('/Users/adhyutabuananda/Library/Mobile Documents/com~apple~CloudDocs/BUZZMEKK/Productivity/Project/credit-scoring-pd-model/dataset/raw/GiveMeSomeCredit-training.csv')

In [13]:
df_train.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [14]:
df_train.drop('Unnamed: 0', axis=1, inplace=True)

In [15]:
col_rename = {
    'SeriousDlqin2yrs':                         'default',
    'RevolvingUtilizationOfUnsecuredLines':      'utilization',
    'age':                                       'age',
    'NumberOfTime30-59DaysPastDueNotWorse':      'past_due_30_59',
    'DebtRatio':                                 'debt_ratio',
    'MonthlyIncome':                             'monthly_income',
    'NumberOfOpenCreditLinesAndLoans':           'open_credit_lines',
    'NumberOfTimes90DaysLate':                   'past_due_90',
    'NumberRealEstateLoansOrLines':              'real_estate_loans',
    'NumberOfTime60-89DaysPastDueNotWorse':      'past_due_60_89',
    'NumberOfDependents':                        'num_dependents'
}
df_train.rename(columns=col_rename, inplace=True)

In [16]:
df_train.head()

,default,utilization,age,past_due_30_59,debt_ratio,monthly_income,open_credit_lines,past_due_90,real_estate_loans,past_due_60_89,num_dependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

### Erklärung der Merkmale

| Merkmale | Beschreibung | Kontext |
| --- | --- | --- |
| default | **Target**: Ausfall | Ausfallbezeichnung (1 = Ausfall) |
| utilization | Kreditkartennutzung | Kreditauslastung |
| past_due_30/60/90 | Anzahl der Zahlungsverzögerungen | Verstöße in der Vergangenheit |
| debt_ratio | Schulden-Einkommens-Verhältnis | DTI-Verhältnis |
| monthly_income | Monatliche Einkommen | Einkommensnachweis |
| num_dependents | Anzahl der Angehörigen | Haushaltrisikofaktor |